[package]
name = "mtdi"
version = "0.1.0"
edition = "2021"
description = "Zero-privilege user-space dynamic instrumentation for macOS (AArch64 inline hooks, dyld injection, JIT-compiled Rust probes)"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
mach2 = "0.4"
syn = { version = "3.0.3", features = ["full", "visit"] }

[lib]
name = "mtdi_lib"
crate-type = ["cdylib", "rlib"]
